[build]
  publish   = "frontend"
  functions = "netlify/functions"

[functions]
  directory = "netlify/functions"
  included_files = ["bot.js"] # bundle your script with the function
  node_bundler = "esbuild"

[functions."one-cent-gala-to-usdc"]
  schedule = "*/10 * * * *"   # every 10 minutes (UTC)
